from __future__ import annotations

import math
from dataclasses import dataclass
from enum import Enum
from typing import List, Sequence


class Domain(str, Enum):
    """
    This class generated by Claude.ai at 2026-06-19 (1405-03-29).

    Frequency domain for poles, zeros, and normalization factor.
    """

    RAD = "rad"   # angular frequency  s = i*omega  [rad/s]
    HZ  = "hz"    # ordinary frequency s = i*2*pi*f [Hz]

    def unit_label(self) -> str:
        """Human-readable unit string."""
        return "rad/s" if self is Domain.RAD else "Hz"


@dataclass
class InstrumentResponse:
    """
    This class generated by Claude.ai at 2026-06-19 (1405-03-29).

    Utilities for converting seismic instrument response parameters
    (poles, zeros, sensitivity, normalization factor) between the
    radian (rad/s) and hertz (Hz) domains.

    Convention  (SEED / StationXML standard)
    -----------------------------------------
    The transfer function is factored as:

        H(s) = Sd * A0 * prod(s - z_i) / prod(s - p_j)

    where
        Sd  = overall sensitivity  [e.g. V·s/m, counts/(m/s)]
        A0  = normalization factor  (dimensionless scalar)
        p_j = poles
        z_i = zeros
        s   = i*omega  [rad/s]  OR  i*2*pi*f  [Hz]  — depending on domain

    A0 is chosen so that the *normalised* transfer function equals 1 at
    the reference frequency f_ref:

        A0 * |prod(s_ref - z_i) / prod(s_ref - p_j)| = 1

    Because of this definition, A0 **changes** when the domain is switched,
    while Sd (sensitivity/gain) is domain-independent.

    Parameters
    ----------
    poles : list of complex
        Poles of the transfer function expressed in ``domain``.
    zeros : list of complex
        Zeros of the transfer function expressed in ``domain``.
    sensitivity : float
        Overall instrument sensitivity (Sd).
        Unit depends on sensor/digitiser type, e.g.:
          * velocity sensor  →  V·s/m  or  counts/(m/s)
          * acceleration     →  V·s²/m
        **Sensitivity is domain-independent; it never changes.**
    normalization_factor : float
        A0 — scalar that satisfies
        ``A0 * |prod(s_ref - z_i) / prod(s_ref - p_j)| == 1``
        at the reference frequency.  *Does* depend on domain.
    domain : Domain
        Whether poles / zeros / A0 are in rad/s or Hz.
    normalization_frequency : float, optional
        Reference frequency used to define A0, expressed in the
        **same unit as ``domain``** (rad/s or Hz).  Defaults to 1.0.
    channel : str, optional
        SEED channel code for bookkeeping, e.g. ``"BHZ"``.

    Example
    ----------
    # STS-2 broadband seismometer — source: rad/s
    >>> sts2_rad = InstrumentResponse(
    ...    poles=[
    ...        complex(-3.700912e-02, +3.700912e-02),
    ...        complex(-3.700912e-02, -3.700912e-02),
    ...        complex(-2.513274e+02, +0.000000e+00),
    ...        complex(-1.310400e+02, +4.672900e+02),
    ...        complex(-1.310400e+02, -4.672900e+02),
    ...    ],
    ...    zeros=[complex(0, 0), complex(0, 0)],
    ...    sensitivity=1500.0,
    ...    normalization_factor=5.9196e+07,  # exact A0 at 1 rad/s
    ...    domain=Domain.RAD,
    ...    normalization_frequency=1.0,        # 1 rad/s ≈ 0.159 Hz
    ...    channel="BHZ",
    ... )
    >>> print(sts2_rad)
    >>> sts2_hz = sts2_rad.to_hz()
    >>> print(sts2_hz)
    >>> sts2_round_trip_back = sts2_hz.to_rad()
    >>> print(sts2_round_trip_back)

    References
    ----------
    - SEED Reference Manual v2.4, Appendix C
    - FDSN StationXML schema (https://www.fdsn.org/xml/station/)
    - Havskov & Ottemöller, "Routine Data Processing in Earthquake Seismology" (2010)
    """

    poles: List[complex]
    zeros: List[complex]
    sensitivity: float
    normalization_factor: float
    domain: Domain
    normalization_frequency: float = 1.0
    channel: str = ""

    # ------------------------------------------------------------------
    # Derived properties
    # ------------------------------------------------------------------

    @property
    def n_poles(self) -> int:
        """Number of poles (Np)."""
        return len(self.poles)

    @property
    def n_zeros(self) -> int:
        """Number of zeros (Nz)."""
        return len(self.zeros)

    # ------------------------------------------------------------------
    # Domain conversion
    # ------------------------------------------------------------------

    def to_domain(self, target: Domain) -> "InstrumentResponse":
        """
        Return a new :class:`InstrumentResponse` in *target* domain.

        If ``self.domain == target`` the same object is returned (no copy).

        Conversion rules  (let TWO_PI = 2*pi,  Np = #poles,  Nz = #zeros)
        -------------------------------------------------------------------
        RAD → HZ (divide by 2π): 
            p_hz = p_rad / TWO_PI
            z_hz = z_rad / TWO_PI
            f_hz = f_rad / TWO_PI
            A0_hz = A0_rad * TWO_PI^(Nz - Np)

        HZ → RAD (multiply by 2π): 
            p_rad = p_hz * TWO_PI
            z_rad = z_hz * TWO_PI
            f_rad = f_hz * TWO_PI
            A0_rad = A0_hz * TWO_PI^(Np - Nz)

        Sensitivity (Sd) is identical in both domains (is copied unchanged in both directions).

        Parameters
        ----------
        target : Domain
            Desired output domain.

        Returns
        -------
        InstrumentResponse
            New instance expressed in *target* domain.
        """
        if self.domain == target:
            return self

        TWO_PI = 2.0 * math.pi

        if self.domain == Domain.RAD and target == Domain.HZ:
            factor      = 1.0 / TWO_PI
            a0_exponent = self.n_zeros - self.n_poles   # e.g. 2 - 3 = -1
        else:
            factor      = TWO_PI
            a0_exponent = self.n_poles - self.n_zeros   # e.g. 3 - 2 = +1

        return InstrumentResponse(
            poles                  = [p * factor for p in self.poles],
            zeros                  = [z * factor for z in self.zeros],
            sensitivity            = self.sensitivity,                   # unchanged
            normalization_factor   = self.normalization_factor * (TWO_PI ** a0_exponent),
            domain                 = target,
            normalization_frequency= self.normalization_frequency * factor,
            channel                = self.channel,
        )

    def to_rad(self) -> "InstrumentResponse":
        """Convert to rad/s domain.  Returns *self* if already in rad/s."""
        return self.to_domain(Domain.RAD)

    def to_hz(self) -> "InstrumentResponse":
        """Convert to Hz domain.  Returns *self* if already in Hz."""
        return self.to_domain(Domain.HZ)

    # ------------------------------------------------------------------
    # Normalization check
    # ------------------------------------------------------------------

    def check_normalization(self, tol: float = 1e-3) -> bool:
        """
        Verify that A0 satisfies the normalisation condition at f_ref.

        The standard (SEED) definition requires:

        .. code-block:: text

            A0 * |prod(s_ref - z_i) / prod(s_ref - p_j)| == 1.0

        Parameters
        ----------
        tol : float
            Relative tolerance (default 0.1 %).

        Returns
        -------
        bool
            ``True`` if the condition holds within *tol*.
        """
        s_ref = complex(0.0, self.normalization_frequency)

        numerator   = math.prod(abs(s_ref - z) for z in self.zeros) \
                      if self.zeros else 1.0
        denominator = math.prod(abs(s_ref - p) for p in self.poles) \
                      if self.poles else 1.0

        value = abs(self.normalization_factor) * numerator / denominator
        return abs(value - 1.0) < tol

    def compute_normalization_factor(self) -> float:
        """
        Compute the theoretically correct A0 from the current poles, zeros,
        and reference frequency.

        Returns
        -------
        float
            A0 such that ``A0 * |prod(s_ref - z_i) / prod(s_ref - p_j)| == 1``.
        """
        s_ref = complex(0.0, self.normalization_frequency)
        numerator   = math.prod(abs(s_ref - z) for z in self.zeros) \
                      if self.zeros else 1.0
        denominator = math.prod(abs(s_ref - p) for p in self.poles) \
                      if self.poles else 1.0
        return denominator / numerator

    # ------------------------------------------------------------------
    # Frequency response evaluation
    # ------------------------------------------------------------------

    def evaluate(self, frequencies: Sequence[float]) -> List[complex]:
        """
        Evaluate the full transfer function H(f) at the given frequencies.

        Frequencies must be in **the same domain** as poles/zeros
        (rad/s if ``domain == Domain.RAD``, Hz if ``domain == Domain.HZ``).

        .. code-block:: text

            H(s) = Sd * A0 * prod(s - z_i) / prod(s - p_j)

        Parameters
        ----------
        frequencies : sequence of float
            Frequencies at which to evaluate H.

        Returns
        -------
        list of complex
            Complex transfer-function values (same length as *frequencies*).
        """
        results: List[complex] = []
        scale = complex(self.normalization_factor * self.sensitivity, 0.0)

        for f in frequencies:
            s   = complex(0.0, f)
            num = scale * math.prod((s - z) for z in self.zeros) \
                  if self.zeros else scale
            den = math.prod((s - p) for p in self.poles) \
                  if self.poles else complex(1.0)
            results.append(num / den if den != 0 else complex(float("inf")))

        return results

    # ------------------------------------------------------------------
    # Display
    # ------------------------------------------------------------------

    def summary(self) -> str:
        """Return a formatted multi-line summary string."""
        unit = self.domain.unit_label()
        lines = [
            f"InstrumentResponse  [{self.channel or 'unnamed'}]  "
            f"domain = {unit}",
            f"  sensitivity            : {self.sensitivity}",
            f"  normalization_factor   : {self.normalization_factor:.8g}",
            f"  normalization_freq     : {self.normalization_frequency} {unit}",
            f"  poles ({self.n_poles}):",
        ]
        for p in self.poles:
            lines.append(f"      {p.real:+.8f}  {p.imag:+.8f}j")
        lines.append(f"  zeros ({self.n_zeros}):")
        for z in self.zeros:
            lines.append(f"      {z.real:+.8f}  {z.imag:+.8f}j")
        ok = self.check_normalization()
        lines.append(f"  normalization check    : {'PASS' if ok else 'FAIL'}")
        return "\n".join(lines)

    def __repr__(self) -> str:
        return self.summary()
